<a href="https://colab.research.google.com/github/Ugo-Ogbodo/Personal_learns/blob/main/DL4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
def activation(x):
  """ Sigmoid activation function
      
      Arguments
      ---------
      x: torch.Tensor
  """
  return 1/(1+torch.exp(-x))

In [ ]:
torch.manual_seed(7)
features = torch.randn((1, 5))
weights = torch.randn_like(features)
bias = torch.randn((1, 1))

In [ ]:
y= activation(torch.sum(features * weights) + bias)
print(y)
##OR
#y = activation((features * weights).sum + bias)

tensor([[0.1595]])


using matrix multiplication is better and faster
 ```torch.mm```<- this recomended for well shaped matrices or ```torch.matmul```
 to shape a tensor use 

```tensor.shape```

to reshape use  ```weights.reshape(a, b)```, ```weights.resize_(a, b)``` and ```weights.view(a, b)```


In [ ]:
y = activation(torch.mm(features, weights.view(5, 1)) + bias)
print(y)

tensor([[0.1595]])


**stacking up**

this is basically creating a hidden layer (nueral networks) for a better working model

In [ ]:
torch.manual_seed(7)
features = torch.randn((1, 3))
n_input = features.shape[1]
n_hidden = 2
n_output = 1

w1 = torch.randn(n_input, n_hidden)
w2 = torch.randn(n_hidden, n_output)

b1 = torch.randn((1, n_hidden))
b2 = torch.randn((1, n_output))

In [ ]:
h = activation(torch.mm(features, w1) + b1)
output = activation(torch.mm(h, w2) + b2)
print(output)

tensor([[0.3171]])


you can always convert from numpy arrays to torch tensors easily with pyTorch 

In [ ]:
import numpy as np

In [ ]:
a = np.random.rand(4, 3)
a

array([[0.26463339, 0.01810223, 0.24321379],
       [0.3652548 , 0.88933555, 0.14566805],
       [0.73105742, 0.35093191, 0.7905384 ],
       [0.07102019, 0.20972768, 0.5677168 ]])

In [ ]:
b = torch.from_numpy(a)
b

tensor([[0.2646, 0.0181, 0.2432],
        [0.3653, 0.8893, 0.1457],
        [0.7311, 0.3509, 0.7905],
        [0.0710, 0.2097, 0.5677]], dtype=torch.float64)

In [ ]:
b.numpy()

array([[0.26463339, 0.01810223, 0.24321379],
       [0.3652548 , 0.88933555, 0.14566805],
       [0.73105742, 0.35093191, 0.7905384 ],
       [0.07102019, 0.20972768, 0.5677168 ]])

the memory between b and a is sheared so performing an inplace action on any will affect the other

In [ ]:
b.mul_(2)

tensor([[0.5293, 0.0362, 0.4864],
        [0.7305, 1.7787, 0.2913],
        [1.4621, 0.7019, 1.5811],
        [0.1420, 0.4195, 1.1354]], dtype=torch.float64)

In [ ]:
a

array([[0.52926677, 0.03620447, 0.48642759],
       [0.73050961, 1.77867109, 0.29133609],
       [1.46211485, 0.70186381, 1.5810768 ],
       [0.14204038, 0.41945535, 1.13543359]])